#!/usr/bin/env python3
"""Generate service contracts from shared/failures.json."""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
FAILURES_SOURCE = ROOT / "shared" / "failures.json"
PERSONAS_SOURCE = ROOT / "shared" / "personas.json"
TS_TARGET = ROOT / "web" / "src" / "types" / "failures.ts"
PERSONAS_TS_TARGET = ROOT / "web" / "src" / "types" / "personas.ts"
PY_TARGET = ROOT / "api" / "models.py"
SQL_TARGET = ROOT / "api" / "schema.sql"
HEADER = "DO NOT EDIT — generated by scripts/codegen.py"

FAILURE_REQUIRED_FIELDS = {
    "code",
    "portalText",
    "plain",
    "brokenLink",
    "office",
    "documents",
    "script",
    "typicalDays",
    "canSelfFix",
}

PERSONA_REQUIRED_FIELDS = {
    "regNo",
    "name",
    "village",
    "district",
    "installmentsReceived",
    "lastInstallmentDate",
    "failureCode",
    "linkage",
}

LINKAGE_FIELDS = {
    "aadhaarSeeded",
    "bankLinked",
    "landSeeded",
    "ekycDone",
}


def load_failures() -> list[dict[str, Any]]:
    payload = json.loads(FAILURES_SOURCE.read_text(encoding="utf-8"))
    failures = payload.get("failures")
    if not isinstance(failures, list) or not failures:
        raise ValueError("shared/failures.json must contain a non-empty failures array")

    codes: list[str] = []
    for index, failure in enumerate(failures):
        if not isinstance(failure, dict):
            raise ValueError(f"failures[{index}] must be an object")
        missing = FAILURE_REQUIRED_FIELDS - failure.keys()
        if missing:
            names = ", ".join(sorted(missing))
            raise ValueError(f"failures[{index}] is missing required fields: {names}")
        code = failure["code"]
        if not isinstance(code, str) or not code:
            raise ValueError(f"failures[{index}].code must be a non-empty string")
        codes.append(code)

    duplicates = sorted({code for code in codes if codes.count(code) > 1})
    if duplicates:
        raise ValueError(f"failure codes must be unique: {', '.join(duplicates)}")

    return failures


def validate_localized_text(value: Any, path: str) -> None:
    if not isinstance(value, dict) or set(value) != {"hi", "en"}:
        raise ValueError(f"{path} must contain exactly hi and en strings")
    if not all(isinstance(value[key], str) and value[key] for key in ("hi", "en")):
        raise ValueError(f"{path}.hi and {path}.en must be non-empty strings")


def expected_linkage(broken_link: str) -> dict[str, bool]:
    linkage = {field: True for field in LINKAGE_FIELDS}
    field_by_broken_link = {
        "aadhaar": "aadhaarSeeded",
        "bank": "bankLinked",
        "land": "landSeeded",
        "ekyc": "ekycDone",
        "eligibility": None,
    }
    if broken_link not in field_by_broken_link:
        raise ValueError(f"unsupported brokenLink value: {broken_link}")
    broken_field = field_by_broken_link[broken_link]
    if broken_field is not None:
        linkage[broken_field] = False
    return linkage


def load_personas(failures: list[dict[str, Any]]) -> list[dict[str, Any]]:
    payload = json.loads(PERSONAS_SOURCE.read_text(encoding="utf-8"))
    personas = payload.get("personas")
    if not isinstance(personas, list) or len(personas) != 8:
        raise ValueError("shared/personas.json must contain exactly 8 personas")

    expected_reg_nos = [f"UP-DEMO-{index:04d}" for index in range(1, 9)]
    actual_reg_nos: list[str] = []
    failure_codes: list[str] = []
    failures_by_code = {failure["code"]: failure for failure in failures}

    for index, persona in enumerate(personas):
        path = f"personas[{index}]"
        if not isinstance(persona, dict):
            raise ValueError(f"{path} must be an object")
        missing = PERSONA_REQUIRED_FIELDS - persona.keys()
        if missing:
            names = ", ".join(sorted(missing))
            raise ValueError(f"{path} is missing required fields: {names}")

        reg_no = persona["regNo"]
        if not isinstance(reg_no, str):
            raise ValueError(f"{path}.regNo must be a string")
        actual_reg_nos.append(reg_no)

        for field in ("name", "village", "district"):
            validate_localized_text(persona[field], f"{path}.{field}")

        installments = persona["installmentsReceived"]
        if (
            not isinstance(installments, int)
            or isinstance(installments, bool)
            or installments < 0
        ):
            raise ValueError(f"{path}.installmentsReceived must be a non-negative int")

        last_installment_date = persona["lastInstallmentDate"]
        if not isinstance(last_installment_date, str):
            raise ValueError(f"{path}.lastInstallmentDate must be an ISO date string")
        try:
            date.fromisoformat(last_installment_date)
        except ValueError as error:
            raise ValueError(
                f"{path}.lastInstallmentDate must be an ISO date string"
            ) from error

        failure_code = persona["failureCode"]
        if not isinstance(failure_code, str) or failure_code not in failures_by_code:
            raise ValueError(
                f"{path}.failureCode must exist in shared/failures.json"
            )
        failure_codes.append(failure_code)

        linkage = persona["linkage"]
        if not isinstance(linkage, dict) or set(linkage) != LINKAGE_FIELDS:
            raise ValueError(f"{path}.linkage must contain exactly four linkage fields")
        if not all(isinstance(value, bool) for value in linkage.values()):
            raise ValueError(f"{path}.linkage values must all be booleans")

        broken_link = failures_by_code[failure_code]["brokenLink"]
        expected = expected_linkage(broken_link)
        if linkage != expected:
            raise ValueError(
                f"{path}.linkage is inconsistent with {failure_code} "
                f"(brokenLink={broken_link})"
            )

    if actual_reg_nos != expected_reg_nos:
        raise ValueError("persona regNo values must be UP-DEMO-0001 through UP-DEMO-0008")
    if len(set(failure_codes)) != len(failure_codes):
        raise ValueError("every persona must use a different failureCode")

    return personas


def render_typescript(failures: list[dict[str, Any]]) -> str:
    codes = " | ".join(json.dumps(item["code"]) for item in failures)
    data = json.dumps(failures, ensure_ascii=False, indent=2)
    return f"""// {HEADER}

export type FailureCode = {codes};

export interface LocalizedText {{
  readonly hi: string;
  readonly en: string;
}}

export interface Failure {{
  readonly code: FailureCode;
  readonly portalText: string;
  readonly plain: LocalizedText;
  readonly brokenLink: string;
  readonly office: LocalizedText;
  readonly documents: readonly LocalizedText[];
  readonly script: LocalizedText;
  readonly typicalDays: number;
  readonly canSelfFix: boolean;
}}

const failures: readonly Failure[] = {data};

export default failures;
"""


def render_personas_typescript(personas: list[dict[str, Any]]) -> str:
    data = json.dumps(personas, ensure_ascii=False, indent=2)
    return f"""// {HEADER}

import type {{ FailureCode, LocalizedText }} from "./failures";

export interface Linkage {{
  readonly aadhaarSeeded: boolean;
  readonly bankLinked: boolean;
  readonly landSeeded: boolean;
  readonly ekycDone: boolean;
}}

export interface Persona {{
  readonly regNo: string;
  readonly name: LocalizedText;
  readonly village: LocalizedText;
  readonly district: LocalizedText;
  readonly installmentsReceived: number;
  readonly lastInstallmentDate: string;
  readonly failureCode: FailureCode;
  readonly linkage: Linkage;
}}

const personas: readonly Persona[] = {data};

export default personas;
"""


def render_python(failures: list[dict[str, Any]]) -> str:
    enum_members = "\n".join(
        f'    {item["code"]} = "{item["code"]}"' for item in failures
    )
    return f'''# {HEADER}

from enum import Enum

from pydantic import BaseModel, ConfigDict


class FailureCode(str, Enum):
{enum_members}


class LocalizedText(BaseModel):
    model_config = ConfigDict(frozen=True)

    hi: str
    en: str


class Failure(BaseModel):
    model_config = ConfigDict(frozen=True)

    code: FailureCode
    portalText: str
    plain: LocalizedText
    brokenLink: str
    office: LocalizedText
    documents: list[LocalizedText]
    script: LocalizedText
    typicalDays: int
    canSelfFix: bool
'''


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render_sql(failures: list[dict[str, Any]]) -> str:
    enum_values = ",\n        ".join(sql_literal(item["code"]) for item in failures)
    return f"""-- {HEADER}

DO $$
BEGIN
    CREATE TYPE failure_code AS ENUM (
        {enum_values}
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS tracker (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    registration_number TEXT NOT NULL,
    failure_code failure_code NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    reminder_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (registration_number, failure_code)
);
"""


def write_generated(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> None:
    failures = load_failures()
    personas = load_personas(failures)
    write_generated(TS_TARGET, render_typescript(failures))
    write_generated(PERSONAS_TS_TARGET, render_personas_typescript(personas))
    write_generated(PY_TARGET, render_python(failures))
    write_generated(SQL_TARGET, render_sql(failures))
    print(
        f"Generated contracts for {len(failures)} failure codes "
        f"and {len(personas)} personas."
    )


if __name__ == "__main__":
    main()
