#!/usr/bin/env python3
"""Generate service contracts from shared/failures.json."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "shared" / "failures.json"
TS_TARGET = ROOT / "web" / "src" / "types" / "failures.ts"
PY_TARGET = ROOT / "api" / "models.py"
SQL_TARGET = ROOT / "api" / "schema.sql"
HEADER = "DO NOT EDIT — generated by scripts/codegen.py"

REQUIRED_FIELDS = {
    "code",
    "portalText",
    "plain",
    "brokenLink",
    "office",
    "documents",
    "script",
    "typicalDays",
    "canSelfFix",
}


def load_failures() -> list[dict[str, Any]]:
    payload = json.loads(SOURCE.read_text(encoding="utf-8"))
    failures = payload.get("failures")
    if not isinstance(failures, list) or not failures:
        raise ValueError("shared/failures.json must contain a non-empty failures array")

    codes: list[str] = []
    for index, failure in enumerate(failures):
        if not isinstance(failure, dict):
            raise ValueError(f"failures[{index}] must be an object")
        missing = REQUIRED_FIELDS - failure.keys()
        if missing:
            names = ", ".join(sorted(missing))
            raise ValueError(f"failures[{index}] is missing required fields: {names}")
        code = failure["code"]
        if not isinstance(code, str) or not code:
            raise ValueError(f"failures[{index}].code must be a non-empty string")
        codes.append(code)

    duplicates = sorted({code for code in codes if codes.count(code) > 1})
    if duplicates:
        raise ValueError(f"failure codes must be unique: {', '.join(duplicates)}")

    return failures


def render_typescript(failures: list[dict[str, Any]]) -> str:
    codes = " | ".join(json.dumps(item["code"]) for item in failures)
    data = json.dumps(failures, ensure_ascii=False, indent=2)
    return f"""// {HEADER}

export type FailureCode = {codes};

export interface LocalizedText {{
  readonly hi: string;
  readonly en: string;
}}

export interface Failure {{
  readonly code: FailureCode;
  readonly portalText: string;
  readonly plain: LocalizedText;
  readonly brokenLink: string;
  readonly office: LocalizedText;
  readonly documents: readonly LocalizedText[];
  readonly script: LocalizedText;
  readonly typicalDays: number;
  readonly canSelfFix: boolean;
}}

const failures: readonly Failure[] = {data};

export default failures;
"""


def render_python(failures: list[dict[str, Any]]) -> str:
    enum_members = "\n".join(
        f'    {item["code"]} = "{item["code"]}"' for item in failures
    )
    return f'''# {HEADER}

from enum import Enum

from pydantic import BaseModel, ConfigDict


class FailureCode(str, Enum):
{enum_members}


class LocalizedText(BaseModel):
    model_config = ConfigDict(frozen=True)

    hi: str
    en: str


class Failure(BaseModel):
    model_config = ConfigDict(frozen=True)

    code: FailureCode
    portalText: str
    plain: LocalizedText
    brokenLink: str
    office: LocalizedText
    documents: list[LocalizedText]
    script: LocalizedText
    typicalDays: int
    canSelfFix: bool
'''


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render_sql(failures: list[dict[str, Any]]) -> str:
    enum_values = ",\n        ".join(sql_literal(item["code"]) for item in failures)
    return f"""-- {HEADER}

DO $$
BEGIN
    CREATE TYPE failure_code AS ENUM (
        {enum_values}
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS tracker (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    registration_number TEXT NOT NULL,
    failure_code failure_code NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    reminder_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (registration_number, failure_code)
);
"""


def write_generated(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> None:
    failures = load_failures()
    write_generated(TS_TARGET, render_typescript(failures))
    write_generated(PY_TARGET, render_python(failures))
    write_generated(SQL_TARGET, render_sql(failures))
    print(f"Generated contracts for {len(failures)} failure codes.")


if __name__ == "__main__":
    main()
