# DO NOT EDIT — generated by scripts/codegen.py

from enum import Enum

from pydantic import BaseModel, ConfigDict


class FailureCode(str, Enum):
    NPCI_NOT_MAPPED = "NPCI_NOT_MAPPED"
    EKYC_PENDING = "EKYC_PENDING"
    LAND_NOT_SEEDED = "LAND_NOT_SEEDED"
    NAME_MISMATCH = "NAME_MISMATCH"
    INVALID_IFSC = "INVALID_IFSC"
    ACCOUNT_DORMANT = "ACCOUNT_DORMANT"
    INVALID_ACCOUNT = "INVALID_ACCOUNT"
    PHYSICAL_VERIFICATION_PENDING = "PHYSICAL_VERIFICATION_PENDING"
    FLAGGED_INCOME_TAX = "FLAGGED_INCOME_TAX"
    FLAGGED_INSTITUTIONAL = "FLAGGED_INSTITUTIONAL"
    DUPLICATE_BENEFICIARY = "DUPLICATE_BENEFICIARY"
    RECOVERY_PENDING = "RECOVERY_PENDING"


class LocalizedText(BaseModel):
    model_config = ConfigDict(frozen=True)

    hi: str
    en: str


class Failure(BaseModel):
    model_config = ConfigDict(frozen=True)

    code: FailureCode
    portalText: str
    plain: LocalizedText
    brokenLink: str
    office: LocalizedText
    documents: list[LocalizedText]
    script: LocalizedText
    typicalDays: int
    canSelfFix: bool
