-- DO NOT EDIT — generated by scripts/codegen.py

DO $$
BEGIN
    CREATE TYPE failure_code AS ENUM (
        'NPCI_NOT_MAPPED',
        'EKYC_PENDING',
        'LAND_NOT_SEEDED',
        'NAME_MISMATCH',
        'INVALID_IFSC',
        'ACCOUNT_DORMANT',
        'INVALID_ACCOUNT',
        'PHYSICAL_VERIFICATION_PENDING',
        'FLAGGED_INCOME_TAX',
        'FLAGGED_INSTITUTIONAL',
        'DUPLICATE_BENEFICIARY',
        'RECOVERY_PENDING'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS tracker (
    session_id UUID NOT NULL,
    reg_no TEXT NOT NULL,
    failure_code failure_code NOT NULL,
    marked_done_at TIMESTAMPTZ,
    reminder_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (session_id, reg_no)
);
