-- DO NOT EDIT — generated by scripts/codegen.py

DO $$
BEGIN
    CREATE TYPE failure_code AS ENUM (
        'NPCI_NOT_MAPPED',
        'EKYC_PENDING',
        'LAND_NOT_SEEDED',
        'NAME_MISMATCH',
        'INVALID_IFSC',
        'ACCOUNT_DORMANT',
        'INVALID_ACCOUNT',
        'PHYSICAL_VERIFICATION_PENDING',
        'FLAGGED_INCOME_TAX',
        'FLAGGED_INSTITUTIONAL',
        'DUPLICATE_BENEFICIARY',
        'RECOVERY_PENDING'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS tracker (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    registration_number TEXT NOT NULL,
    failure_code failure_code NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    reminder_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (registration_number, failure_code)
);
